#:schema node_modules/wrangler/config-schema.json
name = "salario"
compatibility_date = "2024-09-03"
pages_build_output_dir = "./build/client"


[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "salario"
database_id = "f9b39f20-e1b5-4bd9-a545-10bb42cc4479"